//Get All Users 
//Este endpoint serve para acessar os dados gerais de todos os usuários cadastrados. 
GET http://localhost:3003/users
Content-Type: application/json
###

//Get All Products funcionalidade 1 
//Este endpoint serve para acessar os dados gerais de todos os produtos cadastrados.
GET http://localhost:3003/products/
Content-Type: application/json
###


//Get All Products Search funcionalidade 2
//Este endpoint serve para acessar os dados gerais do produto cadastrado pelo nome do produto.
GET http://localhost:3003/products/search?q=celular
Content-Type: application/json

###

//Get Purchase by id
//Este endpoint serve para buscar o pedido através do id do pedido 
GET http://localhost:3003/purchases/b001
Content-Type: application/json

###

