// //Create User 
POST http://localhost:3003/users
Content-Type: application/json

{
    "id": "u06",
    "name": "Davi",
    "email": "davi@gmail.com",
    "password": "123456"
}
###



//Create Product (não estou conseguindo passar o enum)
POST http://localhost:3003/products
Content-Type: application/json

{
    "id": "p007",
    "name": "relógio",
    "price": 900,
    "description": "A prova de água",
    "category": "Eletrônicos",
    "image_url": "https://linkaqui"
}
###

// Create Purchase 
POST http://localhost:3003/purchases
Content-Type: application/json

{
    "userId": "01",
    "productId": "101",
    "quantity": 1,
    "totalPrice": 280
}
###