//Create User 
// Este endpoint serve para criar um usuário novo.
POST http://localhost:3003/users
Content-Type: application/json

{
    "id": "u12",
    "name": "Carla",
    "email": "carla@gmail.com",
    "password": "Euclides1@"
}
###



//Create Product 
// Este endpoint serve para cadastrar um novo produto
POST http://localhost:3003/products
Content-Type: application/json

{
    "id": "p008",
    "name": "calça",
    "price": 150,
    "description": "jeans",
    "image_url": "https://linkaqui"
}
###

//Create Purchase 
//Este endpoint serve para criar um novo pedido de compra
POST http://localhost:3003/purchases
Content-Type: application/json

{
    "id": "b006",
    "buyer_id": "u03",
    "productId": "p004",
    "quantity": 3
}
###