//Edit Product by id 
// Este endpoint serve para editar os dados do produto através do seu id 
PUT http://localhost:3003/products/p001
Content-Type: application/json

{
    "id": "p001",
    "name": "tablet",
    "price": 5000,
    "description": "Com processador Snapdragon 888",
    "image_url": "https://th.bing.com/th/id/OIP.1W1x7YUlXu-YmxypdNeuVAHaE8?pid=ImgDet&rs=1"
  }
###

